#!/bin/bash
readonly ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
docker build -f $ROOT/Dockerfile.oracle-jdk -t islandora/claw-fedora:oracle-jdk $ROOT
docker build -f $ROOT/Dockerfile.open-jdk -t islandora/claw-fedora:open-jdk $ROOT
# Open JDK is the default implementation. 
docker tag islandora/claw-fedora:open-jdk islandora/claw-fedora:latest
